Repository r4sharma/CSE210_Group6, pull requests merged in 2022-12, with the labels that each got.

#100 Create branch-merge.md
  Docs/guidelines/branch-merge.md
Labels: documentation

#139 add last updated to cards
  dist/main.js
  src/components/cards.js
Labels: enhancement

#150 Added instructions for executing Selenium tests
  README.md
Labels: documentation

#174 added icon for export button
  src/index.html
  styles.css
Labels: enhancement

#187 Set max date to current date
  dist/main.js
  src/index.js
Labels: bug
